-- ============================================================
-- 綠源EPC戰情室 Supabase 初始化腳本
-- 使用方式：Supabase Dashboard → SQL Editor → 貼上全部 → Run
-- ============================================================

-- 案場資料表
create table if not exists public.sites (
  id          bigint generated by default as identity primary key,
  name        text not null,
  label       text default '',          -- 地圖短標籤
  region      text default 'north',     -- north / center / south / east
  city        text default '',
  cap         text default '待確認',
  owner       text default '',
  pm          text default '',          -- 工地主任
  type        text default '太陽能',    -- 太陽能 / 儲能 / 太陽能+儲能 / 儀電配管
  addr        text default '',
  mw          numeric default 0,        -- 光電容量 kW
  skw         numeric default 0,        -- 儲能功率 kW
  mwh         numeric default 0,        -- 儲能容量 kWh
  start_date  text default '',          -- YYYY/MM/DD
  end_date    text default '',
  pct         int default 0,
  status      text default 'normal',    -- normal / warn / danger / done
  lng         numeric,                  -- 地圖經度
  lat         numeric,                  -- 地圖緯度
  wbs         jsonb,                    -- WBS 各項完成率 {"整地工程":100, ...}
  created_at  timestamptz default now()
);

-- 工地主任資料表
create table if not exists public.supervisors (
  id     bigint generated by default as identity primary key,
  name   text not null unique,
  color  text default '#3b82f6',
  phone  text default '',
  sites  bigint[] default '{}'          -- 負責的案場 id 清單
);

-- 啟用 Row Level Security
alter table public.sites enable row level security;
alter table public.supervisors enable row level security;

-- 政策：任何人可讀可寫（儀表板不需登入）
create policy "public read sites"         on public.sites       for select using (true);
create policy "public insert sites"       on public.sites       for insert with check (true);
create policy "public update sites"       on public.sites       for update using (true);
create policy "public delete sites"       on public.sites       for delete using (true);
create policy "public read supervisors"   on public.supervisors for select using (true);
create policy "public insert supervisors" on public.supervisors for insert with check (true);
create policy "public update supervisors" on public.supervisors for update using (true);
create policy "public delete supervisors" on public.supervisors for delete using (true);

-- ============================================================
-- 種子資料：現有 17 個案場
-- ============================================================
insert into public.sites (id, name, label, region, city, owner, pm, type, addr, mw, skw, mwh, start_date, end_date, pct, status, lng, lat, wbs) values
(0,  '盛餘屏南太陽能發電系統建置工程',    '盛餘屏南',   'south',  '屏東', '待確認',                 '王主任',        '太陽能',       '屏東縣',                          0,       0,   0,   '2026/02/01', '2026/12/31', 38,  'warn',   120.515, 22.460, null),
(1,  '恩盈太陽光電及儲能系統工程',        '恩盈',       'south',  '屏東', '恩盈企業股份有限公司',   '林志鴻 Daniel', '太陽能+儲能', '屏東縣萬巒鄉佳興路83號',          298.1,   200, 430, '2024/04/01', '2025/10/20', 100, 'done',   120.566, 22.571, null),
(2,  '臺科大華夏校區太陽光電系統建置工程','臺科大華夏', 'north',  '台北', '臺灣科技大學',           '張主任',        '太陽能',       '台北市大安區基隆路四段43號',      0,       0,   0,   '2026/01/01', '2026/09/30', 75,  'normal', 121.493, 24.987, null),
(3,  '板橋果菜市場發電系統工程',          '板橋果菜',   'north',  '新北', '待確認',                 '張主任',        '太陽能',       '新北市板橋區',                    0,       0,   0,   '2026/01/01', '2026/08/31', 55,  'normal', 121.458, 25.013, null),
(4,  '台以八翁太陽光電發電系統工程',      '台以八翁',   'north',  '新北', '待確認',                 '吳主任',        '太陽能',       '新北市',                          0,       0,   0,   '2026/02/01', '2026/10/31', 50,  'warn',   121.770, 25.080, null),
(5,  '兆豐銀行PV及儲能系統建置工程',      '兆豐銀行',   'south',  '高雄', '振興',                   '蕭宏明 Mark',   '太陽能+儲能', '高雄市楠梓區加昌路600-2號',       202.86,  100, 261, '',           '',           33,  'warn',   120.322, 22.728, '{"整地工程":100,"基礎工程":100,"支架安裝":100,"品質檢查":0,"模組安裝":0,"DC配線":0,"DC側":0,"AC側":0,"接地系統":0,"通訊工程":0,"單機測試":0,"系統測試":0,"台電測試":0,"驗收與移交":0}'::jsonb),
(6,  '創弈學甲儲能系統建置工程',          '創弈學甲',   'south',  '台南', '待確認',                 '王主任',        '儲能',         '台南市學甲區',                    0,       0,   0,   '2026/03/01', '2026/10/31', 32,  'warn',   120.181, 23.232, null),
(7,  '精湛光學PV系統建置工程',            '精湛光學',   'center', '台中', '待確認',                 '陳主任',        '太陽能',       '台中市',                          0,       0,   0,   '2026/01/01', '2026/10/31', 65,  'normal', 120.680, 24.160, null),
(8,  '生原家電太陽光電發電系統工程',      '生原家電',   'center', '彰化', '待確認',                 '陳主任',        '太陽能',       '彰化縣',                          0,       0,   0,   '2026/02/01', '2026/09/30', 40,  'warn',   120.540, 24.070, null),
(9,  '東元湖口太陽能建置工程',            '東元湖口',   'north',  '新竹', '東元電機股份有限公司',   '蕭名湶 Dyke',   '太陽能',       '新竹縣湖口鄉新竹工業區中華路15號',1811.34, 0,   0,   '2024/11/11', '2025/09/09', 100, 'done',   121.040, 24.900, null),
(10, '東元觀音二廠太陽能建置工程',        '東元觀音',   'north',  '桃園', '東元電機股份有限公司',   '蕭名湶 Dyke',   '太陽能',       '桃園市觀音區樹林里國建一路6號',   1011.81, 0,   0,   '2024/11/03', '2025/08/14', 100, 'done',   121.080, 25.030, null),
(11, '南陽街微電網系統建置工程',          '南陽街',     'north',  '台北', '待確認',                 '林主任',        '儲能',         '台北市中正區南陽街',              0,       0,   0,   '2026/01/15', '2026/08/15', 45,  'warn',   121.515, 25.044, null),
(12, '台積電AP6B太陽能配置工程',          '台積AP6B',   'north',  '苗栗', '高信工程股份有限公司',   '林則瑜 Jack',   '太陽能',       '苗栗縣竹南鎮科專七路1號',         370.64,  0,   0,   '2024/12/16', '',           35,  'warn',   120.900, 24.700, null),
(13, '亨叡太陽光電系統建置工程',          '亨叡',       'north',  '桃園', '待確認',                 '吳主任',        '太陽能',       '桃園市',                          0,       0,   0,   '2026/02/01', '2026/10/15', 20,  'danger', 121.300, 24.930, null),
(14, '法蘭摩沙整廠儀電及配管工程',        '法蘭摩沙',   'center', '雲林', '待確認',                 '陳主任',        '儀電配管',     '雲林縣',                          0,       0,   0,   '2026/03/01', '2026/11/30', 25,  'danger', 120.350, 23.800, null),
(15, '台積電AP5B太陽能配置工程',          '台積AP5B',   'south',  '台南', '台積電',                 '李主任',        '太陽能',       '台南市新市區',                    0,       0,   0,   '2025/12/01', '2026/09/30', 60,  'normal', 120.290, 23.080, null),
(16, '中科友達儲能系統建置工程',          '中科友達',   'center', '台中', '友達光電',               '李主任',        '儲能',         '台中市西屯區中科',                0,       0,   0,   '2026/02/01', '2026/12/31', 42,  'warn',   120.610, 24.210, null);

-- 讓自動編號接續在種子資料之後
select setval(pg_get_serial_sequence('public.sites','id'), (select max(id) from public.sites));

-- 種子資料：工地主任
insert into public.supervisors (name, color, phone, sites) values
('張主任',      '#3b82f6', '0912-345-678', '{2,3}'),
('蕭宏明 Mark', '#f59e0b', '0927-287-771', '{5}'),
('蕭名湶 Dyke', '#a855f7', '0919-701-453', '{9,10}'),
('林則瑜 Jack', '#14b8a6', '0923-813-779', '{12}'),
('林主任',      '#10b981', '0923-456-789', '{11}'),
('陳主任',      '#8b5cf6', '0934-567-890', '{7,8,14}'),
('王主任',      '#f97316', '0945-678-901', '{0,6}'),
('李主任',      '#ef4444', '0956-789-012', '{15,16}'),
('吳主任',      '#06b6d4', '0967-890-123', '{4,13}');
